# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9abc2f36531e208d030fdea0815ea635cb844a317547e5ee4902c13fde3f0336af67447fadd06e68711b41c949ddd372b717de74f00f5c6ac0ca047c0316af6

test:
  secret_key_base: f155ea3eb0a98137683e2b8ba5097896df0ce62d32c1a01b97ce5c9d2cb6f29010fc8da0e17e0b6efb39584c24f3eca3bd00f7d0485ec1e520fc48888cb53cca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
